#!/usr/bin/env Rscript

#################################################################
#                                                               #
#       This script takes tab-separated text file(s) as         #
#       input, performs a survival test, produces a HR and      #
#       a kaplan-meier style survival curve grapgh (pdf)        #
#       Must have the following columns;                        #
#       Days.OS = Days of overall survival                      #
#       Treatment = Treatment given                             #
#       Death_Binary = Death (1) or Censor (0)                  #
#       Variant_ID = Unique variant descriptor                  #
#                                                               #
#                Made for R v3.1.2                              #
#                                                               #
#################################################################

##### Load the required packages ##### 

y <- c("survival", "tools", "survcomp", "plyr")
lapply(y, require, character.only = TRUE)

##### Take the file location from the command line argument ##### 

args <- commandArgs(trailingOnly = TRUE)
survival.file <- "/Users/iMac5/Desktop/Supplementary_Table_1.txt" # args[1] # read.delim("~/Desktop/Supplementary_Table_1.txt")

##### Get the file name ##### 

filename <- basename(survival.file) # remove extension
region_header <- file_path_sans_ext(filename) # directory 
dir <- dirname(survival.file)

##### Split the input file by variant into list #####

spilt.by.variant <- split(survival.file, f = survival.file$Variant.Summary, drop=TRUE)

##### Assign first element in list to variable then remove it from list #####

for (i in 1:length(spilt.by.variant)){
  if(length(spilt.by.variant[[i]]$Variant.Summary)>100)
    pdf(file.path(dir, paste(spilt.by.variant[[i]]$Variant.Summary, "pdf", sep = ".")))
      plot(survfit(Surv(spilt.by.variant[[i]]$Days.OS, spilt.by.variant[[i]]$Death_Binary == 1) ~ spilt.by.variant[[i]]$Treatment),
        main = spilt.by.variant[[i]]$Variant.Summary[1],
        col.main = "black", xlab = "Time in days",
        ylab = "Overall Survival Proportion",
        col.lab= "blue", cex.lab = 0.9, mark = "+",
        col = c(2, 4), lty = 2:3)
      #legend(300, 1.0, c("Docetaxel 75 mg/m2", "Ganetespib 150 mg/m2 in combination with Docetaxel 75 mg/m2"), cex = 0.6, lty = 2:3,col = c(2, 4)) 
     dev.off()
}
